// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PostgREST.DbContext.Provider.PackageTesting.Models;

[Table("precio")]
[PrimaryKey(nameof(IdCompra), nameof(IdUnidadMedida))]
public class Precio
{
    [Column("idCompra")]
    public int IdCompra { get; set; }

    [Column("idUnidadMedida")]
    public int IdUnidadMedida { get; set; }

    [Column("factor")]
    public decimal Factor { get; set; }

    [Column("divide")]
    public bool Divide { get; set; }

    [Column("precio")]
    public decimal PrecioCol { get; set; }
}
