// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgREST.DbContext.Provider.PackageTesting.Models;

[Table("rate")]
public class Rate
{
    [Key]
    [MaxLength(5)]
    [Column("moneda")]
    public string Moneda { get; set; } = default!;

    [Column("factor")]
    public decimal Factor { get; set; }
}
