// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgREST.DbContext.Provider.PackageTesting.Models;

[Table("persona")]
public class Persona
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [MaxLength(100)]
    [Column("nombre")]
    public string? Nombre { get; set; }
}
