// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgREST.DbContext.Provider.Analyzers.Tests.Models;

[Table("venta")]
public class Venta
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("idProducto")]
    public int IdProducto { get; set; }

    [Column("fecha")]
    public DateOnly Fecha { get; set; }

    [Column("cantidad")]
    public decimal Cantidad { get; set; }

    [Column("idPendiente")]
    public int? IdPendiente { get; set; }

    [Column("idTipoPago")]
    public int IdTipoPago { get; set; }

    [Column("interno")]
    public bool Interno { get; set; }

    [Column("precio")]
    public decimal Precio { get; set; }

    [Required]
    [MaxLength(5)]
    [Column("moneda")]
    public string Moneda { get; set; } = default!;

    [Column("tasa")]
    public decimal Tasa { get; set; }

    [Column("idUnidadMedida")]
    public int IdUnidadMedida { get; set; }
}
