// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgREST.DbContext.Provider.PackageTesting.Models;

[Table("unidadMedida")]
public class UnidadMedida
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [MaxLength(25)]
    [Column("nombre")]
    public string Nombre { get; set; } = default!;

    [Required]
    [MaxLength(5)]
    [Column("simbolo")]
    public string Simbolo { get; set; } = default!;
}
