// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PostgREST.DbContext.Provider.PackageTesting.Models;

[Table("categorizacion")]
[PrimaryKey(nameof(IdProducto), nameof(IdCategoria))]
public class Categorizacion
{
    [Column("idProducto")]
    public int IdProducto { get; set; }

    [Column("idCategoria")]
    public int IdCategoria { get; set; }
}
