// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PostgREST.DbContext.Provider.PackageTesting.Models;

[Table("purchaseSupplier")]
[PrimaryKey(nameof(PurchaseId), nameof(SupplierId))]
public class PurchaseSupplier
{
    [Column("purchaseId")]
    public int PurchaseId { get; set; }

    [Column("supplierId")]
    public int SupplierId { get; set; }

    [Column("purchaseDate")]
    public DateTime? PurchaseDate { get; set; }

    [Column("amount")]
    public decimal? Amount { get; set; }
}
