// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgREST.DbContext.Provider.PackageTesting.Models;

[Table("logs")]
public class Logs
{
    [Key]
    [Column("timestamp")]
    public DateTime Timestamp { get; set; }

    [Required]
    [MaxLength(25)]
    [Column("level")]
    public string Level { get; set; } = default!;

    [Required]
    [Column("message")]
    public string Message { get; set; } = default!;

    [Required]
    [MaxLength(2000)]
    [Column("trace")]
    public string Trace { get; set; } = default!;
}
