// <auto-generated>
//   Generated by PostgREST Schema Designer.
//   Re-run the code fix to regenerate after schema changes.
// </auto-generated>

#nullable enable

using PostgREST.DbContext.Provider.Tests.Models;

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PostgREST.DbContext.Provider.Analyzers.Tests.Models;

[Table("producto")]
public class Producto
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [MaxLength(250)]
    [Column("nombre")]
    public string Nombre { get; set; } = default!;

    public virtual IList<Compra> Compras { get; internal set; } = [];   

    public virtual IList<Venta> Ventas { get; internal set; } = [];
}
